version: '3.9'
services:
  react-app:
    container_name: jerzy-dashboard
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
    ports:
      - '3006:3006'
    environment:
      - CHOKIDAR_USEPOLLING=true

networks:
  default:
    external:
      name: caddy_network
